"""Export utilities for generating downloadable candidate reports and interview kits."""

from typing import Dict, Any


class ReportExporter:
    """Formats interview kits and candidate screening profiles for export."""

    @staticmethod
    def format_interview_kit_markdown(kit_data: Dict[str, Any]) -> str:
        """Formats an interview kit into structured markdown ready for download."""
        lines = []
        candidate_name = kit_data.get("candidate_name", "Candidate")
        target_role = kit_data.get("target_role", "Target Role")
        score = kit_data.get("overall_fit_score", 0)

        lines.append(f"# Interview Kit: {candidate_name}")
        lines.append(f"**Target Role:** {target_role}  ")
        lines.append(f"**Calculated Fit Score:** {score}%  ")
        lines.append("Generated by **AI HR Recruitment Assistant (Agent + Tools + RAG)**\n")
        lines.append("---")

        # 1. Technical Questions
        lines.append("## 1. Technical Architecture & In-Depth Questions\n")
        tech_qs = kit_data.get("technical_questions", [])
        for i, q in enumerate(tech_qs, 1):
            lines.append(f"### Q{i}: {q.get('category')}")
            lines.append(f"**Question:** {q.get('question')}\n")
            if q.get("context"):
                lines.append(f"> **Context/Why Ask:** {q.get('context')}\n")
            rubric = q.get("rubric", {})
            if rubric:
                lines.append("#### Evaluation Rubric:")
                lines.append(f"- **Ideal / Expected Answer:** {rubric.get('ideal_answer')}")
                lines.append(f"- **Watch Outs / Red Flags:** {rubric.get('watch_outs')}\n")

        # 2. Gap & Probe Questions
        lines.append("## 2. Skill Gap & Resume Probe Questions\n")
        gap_qs = kit_data.get("gap_questions", [])
        if gap_qs:
            for i, q in enumerate(gap_qs, 1):
                lines.append(f"### Probe {i}: {q.get('category')}")
                lines.append(f"**Question:** {q.get('question')}\n")
                rubric = q.get("rubric", {})
                if rubric:
                    lines.append(f"- **Ideal Answer:** {rubric.get('ideal_answer')}")
                    lines.append(f"- **Watch Outs:** {rubric.get('watch_outs')}\n")
        else:
            lines.append("*No significant skill gaps identified. Candidate aligns well with core stack.*\n")

        # 3. Behavioral Questions
        lines.append("## 3. Behavioral & STAR Leadership Questions\n")
        beh_qs = kit_data.get("behavioral_questions", [])
        for i, q in enumerate(beh_qs, 1):
            lines.append(f"### Behavioral Q{i}: {q.get('category')}")
            lines.append(f"**Question:** {q.get('question')}\n")
            rubric = q.get("rubric", {})
            if rubric:
                lines.append(f"- **Ideal Answer:** {rubric.get('ideal_answer')}")
                lines.append(f"- **Watch Outs:** {rubric.get('watch_outs')}\n")

        # 4. Scenario Challenge
        scenario = kit_data.get("scenario_challenge", {})
        if scenario:
            lines.append("## 4. Real-World Architecture Scenario Challenge\n")
            lines.append(f"**{scenario.get('title')}**\n")
            lines.append(f"> {scenario.get('scenario')}\n")
            lines.append("**Key Evaluation Dimensions:**")
            for dim in scenario.get("key_evaluation_dimensions", []):
                lines.append(f"- {dim}")

        return "\n".join(lines)
